//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mechanix.Workflow.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mechanix.Workflow.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand is required..
        /// </summary>
        internal static string Car_NoBrand {
            get {
                return ResourceManager.GetString("Car_NoBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner first name is required..
        /// </summary>
        internal static string Car_NoOwnerFirstName {
            get {
                return ResourceManager.GetString("Car_NoOwnerFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner last name is required..
        /// </summary>
        internal static string Car_NoOwnerLastName {
            get {
                return ResourceManager.GetString("Car_NoOwnerLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patent is required.
        /// </summary>
        internal static string Car_NoPatent {
            get {
                return ResourceManager.GetString("Car_NoPatent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is required..
        /// </summary>
        internal static string Car_NoService {
            get {
                return ResourceManager.GetString("Car_NoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year is required..
        /// </summary>
        internal static string Car_NoYear {
            get {
                return ResourceManager.GetString("Car_NoYear", resourceCulture);
            }
        }
    }
}
